name: Sales Achievements
favicon: null
layout_spectrum: 0.40254
typography_spectrum: 0.88567
title: Sales Achievements
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#679ff2'
    - '#3c6bb9'
    - '#9fd4fe'
    - '#132a53'
    - '#788397'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
